### ISSUE TITLE
Issue using multiple accounts on tablet - Logging in

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#148]
On a tablet, we have created multiple user accounts. One is an "administrator" that has access to everything. For the other users, we have limited access to just the ERCC app. If I create an account on the administrator account, and then switch over to the limited user account, there are several issues. One is: 
- If I create an account on the administrator profile, and then switch over to the limited access profile and try to log in with that new user, I get an alert "Wrong login id or password"

For example, on the administrator account, I created: 
username: july
password: 1111
I can successfully login with these credentials on the administrative account. 

On the limited access account, I try to log in with that same user, I get the error.

**Comment by whppawan** [comment]
Both the account behaves like two different tablets.
So before switching the account you need to upload the data to server so that the new account (which behaves like a new tablet) can found the login id in server.
Note : First time login (from login id which has been created from another account of the tablet and uploaded to server) from restricted account needs internet access.

**Comment by space-ravi** [comment]
Thanks
