### ISSUE TITLE
App crash after clicking OK

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#171]
8 tablets are experiencing this issue: The application stops after entering the name of the
health care worker, once you click on the OK button.

Using version 1.02 of app, OS ranges from 4.4.4, 5.02, and 6.01.

**Comment by whppawan** [comment]
Please check if they already logged in or fresh log in on that particular tablet. Because if the login was old then we need to check otherwise it is resolved in version 1.03.

Issue may occurred due to long time taken by tablet to login which has been fixed in version 1.03 which APK i have already sent by mail. If everything is fine in version 1.03 then give us sign of release it.

**Comment by space-ravi** [comment]
My apologies, please go ahead and release version 1.03 of the app. The team will then need to go to Play Store and upload new version?

**Comment by whppawan** [comment]
Yes, they will need to go to Play Store to download new version.

**Comment by space-ravi** [comment]
Ok thanks, please let me know when it is uploaded and ready to download.

**Comment by whppawan** [comment]
Ok
