### ISSUE TITLE
Health worker fields are not saving to db

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#202]
I created a new user (gchen) and filled out all the fields. However, in the database, hcw_area, hcw_zone, hcw_clinic_id, hcw_loc are all blank. (Note, one of those isn't used but I'm not sure if it is hcw_clinic_id or hcw_loc).

**Comment by kamal1978** [comment]
In my case i have created user kamal both hcw_area and zone are populating while hcw_clinic_id is blank, i will check it should populate and hcw_loc is blank, i am not sure what is the use of this field as we are not capturing this information at the registration. Though this was given to us initially as a part of db schema.

Just a question are these HCWs are stationed at a clinic or mapped to group of  clinics, if yes then it make sense to use the hierarchy  Health Zone -> Health Area -> Clinic. All these should be in dropdown, so that HCWs will be mapped to HZ-> HA-> Clinics

**Comment by space-ravi** [comment]
Interesting, I'm not sure why hcw_area, hcw_zone, hcw_clinic_id captured for you but not for any other users (including myself). Can you investigate? 

Let's keep hcw_loc in the db in case we decide to use it later. 

To your question, each clinic is located in a health area (analogous to city) and health zone (analogous to state). Are you suggesting that based on the HZ that the health workers choose from the drop down, that would then populate the corresponding HA's within that HZ for them to choose from? That's fine with me, but sounds more complicated.

**Comment by kamal1978** [comment]
hcw_clinic_id was not populating, that we will check apart from hcw_zone and area got populated on the db, what i did after the registration, i uploaded the data to the server, i think that might have triggered it. will check that.

Yes my suggestion would be to give dropdown, since for the report and for the app we are creating that dropdown structure, it is good we put the dropdown at the time of user registration, it will then map the user to respective HA and HZ, i dont think it would be complicated, if the list is comprehensive.
