### ISSUE TITLE
Issue on radio button screen (UNTA register)

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#320]
On the admin site, go to component "UNTA Dominant Admission".
The radio button should have 4 options: 
- NA with PT < -3 DS or PB < 115 mm
- NA with edema
- NA with relapse
- Other entries

The first entry does not show up on the app. I would guess this is an issue with the "-3" sign? Since "-1" is used to denote the first column, etc.

"Component options" is written as: 
NA with PT < -3 DS or PB < 115 mm-1|NA with edema-1|NA with relapse-1|Other entries-1

Please advise how I can actually have the desired text.

**Comment by dheerajdutta** [comment]
Perhaps, this thing will have to be tested in the application side at the code level because logic is written at Application side.

**Comment by space-ravi** [comment]
Note: Similar issue on screen "BR Blood Group" where we list all potential blood types. Choices should be: 
A+; A-; B+; B-; AB+; AB-; O+; O-

But only the options with the "+" are showing up on the screen.

**Comment by whpVishal** [comment]
Hello @space-ravi , there is only solution i can suggest which is to represent - value as any other specific character, so that it didn't affect the existing logic of columns and while showing the text it will get converted into - sign.
ex: ( representing - as @@)
"NA with PT < -3 DS or PB < 115 mm-1" will be written as "NA with PT < @@3 DS or PB < 115 mm-1" on admin side.
and in app i will convert the @@ as -

i am sending a new build in which you check this change.

**Comment by space-ravi** [comment]
Works as expected. Just a reminder to please update the version number on the login screen for each new APK file.
