### ISSUE TITLE
CPS Vaccination report calculation error

### ISSUE THREAD

**Issue by space-ravi** [kamal1978/LTFHC#348]
In the French language (maybe also in English), there is an error calculating the PVC-13 (3) line. You'll notice that there is 1 male patient and 1 female patient that qualify for this row (see right most cicle). However, in the 0-11 mois columns, there is only a single entry (see left circle). 

See screenshot below. Please check both English and French languages. 
![Screenshot_2020-11-06-20-08-15](https://user-images.githubusercontent.com/9537700/98431752-145b8b80-206d-11eb-8436-c0891aa2fd02.png)

**Comment by whpVishal** [comment]
Hello Ravi, on which user i can see this data.

**Comment by space-ravi** [comment]
rprakash (i should have mentioned this, but my testing is almost always done with that username)

**Comment by whpVishal** [comment]
This Bug has been fixed in latest build i shared. 
i was looking for the data to test but didn't received it while downloading. I tested it by inserting dummy data and it shows the right calculation. Still i have doubt about it, if you have the data please upload it so that i can test it on that too.
